
- hosts: all
  become: true
  vars: 
    testing_debug_strategy: "some_value"
  serial:   # Rolling updates (update a few servers at a time)  # You want to test on a small batch first  # Ensuring some servers stay online during updates 
    - 1      # Test on 1 server first
    - 25%    # Then 25% of remaining
    - 100%   # Then the rest
  strategy: debug  # all options are linear(default), free, debug
  tasks: 
    
    - name: testing a normal loop
      copy: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: yes
      loop: 
        - {src: /home/ansible/tmpdir/1, dest: /tmp/tmpdir2/}
        - {src: /home/ansible/tmpdir/2, dest: /tmp/tmpdir1/}
        - {src: /home/ansible/tmpdir/3, dest: /tmp/tmpdir4/}
        - {src: /home/ansible/tmpdir/4, dest: /tmp/tmpdir3/}
      ignore_errors: false 

    - name: install nginx
      apt: 
        name: nginx
        state: present
        update_cache: true 
        cache_valid_time: 600 

    - name: print some random message
      debug: 
        msg: "all tasks done"