
- name: create ansible user 
  user: 
    name: ansible 
    state: present 
    home: /home/ansible 
    create_home: true 

- name: add pub key to ansible user 
  authorized_key: 
    user: ansible 
    state: present 
    key: "{{ lookup('file', role_path + '/files/.secrets/ansible.pub')}}"

- name: add ansile user to sudoers 
  copy: 
    src: ../files/ansible-sudoer
    dest: /etc/sudoers.d/
    owner: root 
    group: root
    mode: 0400 

- block: 
  - name: disable ssh socket on ubuntu 
    systemd: 
      name: ssh.socket
      state: stopped 
      enabled: false 
      masked: false 

  - name: modify ssh configs
    vars: 
      subsystem_path: "/usr/lib/openssh/sftp-server"
    template: 
      src: ../templates/sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0440 
    notify: restart_ssh_service_ubuntu
  when: ansible_distribution == "Ubuntu"


- block: 
  - name: add custom ssh port to selinux 
    seport: 
      ports: "{{ custom_ssh_port }}"
      proto: tcp
      setype: ssh_port_t
      state: present

  - name: modify ssh configs
    vars: 
      subsystem_path: "/usr/libexec/openssh/sftp-server"
    template: 
      src: ../templates/sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0440 
    notify: restart_ssh_service_fedora
  when: ansible_distribution == "Fedora"