
- name: create ansible user 
  user: 
    name: ansible 
    state: present 
    home: /home/ansible 
    create_home: true 

- name: create .ssh directory for ansible 
  file: 
    state: directory 
    path: /home/ansible/.ssh 

- name: add pub key to ansible user 
  authorized_key: 
    user: ansible 
    state: present 
    key: "{{ lookup('file', role_path + '/files/.secrets/ansible.pub')}}"

- name: add ansile user to sudoers 
  copy: 
    src: ../files/ansible-sudoer
    dest: /etc/sudoers.d/
    owner: root 
    group: root
    mode: 0400 

- name: modify ssh configs
  template: 
    src: ../templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0440 
  notify: restart_ssh_service



