
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Install_Molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Update system packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip python3-venv libssl-dev
      
      - name: Install Molecule and dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install "molecule[docker]" molecule-plugins
          molecule --version
